api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "pricing-function"
type = "function"
uid = "2682ab7f-e78f-fbdb-932c-4bdb59beb0d4679e0592"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
